[output]
format = "colored-line-number"

[linters]
enable = [
    "gosimple", # Suggest code simplifications
    "ineffassign", # Detects unused variable assignments
    "typecheck", # Standard Go type checks
    "unused", # Detect unused constants, variables, functions and types
    "goconst", # Detect repeated values that can be made constants
    "misspell", # Fix spelling errors
    "unconvert", # Detect unnecessary type conversions
    "unparam", # Detect unused function parameters
    "dupl", # Detect duplicate code
]

disable = [
    "errcheck",
]

[issues]
exclude-use-default = false
