// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: internal/microservices/like/proto/like.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PinId  int64 `protobuf:"varint,1,opt,name=pinId,proto3" json:"pinId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *MakeLikeRequest) Reset() {
	*x = MakeLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeLikeRequest) ProtoMessage() {}

func (x *MakeLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeLikeRequest.ProtoReflect.Descriptor instead.
func (*MakeLikeRequest) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{0}
}

func (x *MakeLikeRequest) GetPinId() int64 {
	if x != nil {
		return x.PinId
	}
	return 0
}

func (x *MakeLikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MakeLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid      bool  `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	LocalError int64 `protobuf:"varint,2,opt,name=localError,proto3" json:"localError,omitempty"`
}

func (x *MakeLikeResponse) Reset() {
	*x = MakeLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeLikeResponse) ProtoMessage() {}

func (x *MakeLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeLikeResponse.ProtoReflect.Descriptor instead.
func (*MakeLikeResponse) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{1}
}

func (x *MakeLikeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *MakeLikeResponse) GetLocalError() int64 {
	if x != nil {
		return x.LocalError
	}
	return 0
}

type GetUsersLikedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PinId int64 `protobuf:"varint,1,opt,name=pinId,proto3" json:"pinId,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetUsersLikedRequest) Reset() {
	*x = GetUsersLikedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersLikedRequest) ProtoMessage() {}

func (x *GetUsersLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersLikedRequest.ProtoReflect.Descriptor instead.
func (*GetUsersLikedRequest) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersLikedRequest) GetPinId() int64 {
	if x != nil {
		return x.PinId
	}
	return 0
}

func (x *GetUsersLikedRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname  string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl string `protobuf:"bytes,4,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{3}
}

func (x *UserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetUsersLikedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users      []*UserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Valid      bool            `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	LocalError int64           `protobuf:"varint,3,opt,name=localError,proto3" json:"localError,omitempty"`
}

func (x *GetUsersLikedResponse) Reset() {
	*x = GetUsersLikedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersLikedResponse) ProtoMessage() {}

func (x *GetUsersLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersLikedResponse.ProtoReflect.Descriptor instead.
func (*GetUsersLikedResponse) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersLikedResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUsersLikedResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GetUsersLikedResponse) GetLocalError() int64 {
	if x != nil {
		return x.LocalError
	}
	return 0
}

type CheckIsLikedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PinId  int64 `protobuf:"varint,1,opt,name=pinId,proto3" json:"pinId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CheckIsLikedRequest) Reset() {
	*x = CheckIsLikedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIsLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsLikedRequest) ProtoMessage() {}

func (x *CheckIsLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsLikedRequest.ProtoReflect.Descriptor instead.
func (*CheckIsLikedRequest) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{5}
}

func (x *CheckIsLikedRequest) GetPinId() int64 {
	if x != nil {
		return x.PinId
	}
	return 0
}

func (x *CheckIsLikedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckIsLikedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Liked      bool  `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	Valid      bool  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	LocalError int64 `protobuf:"varint,3,opt,name=localError,proto3" json:"localError,omitempty"`
}

func (x *CheckIsLikedResponse) Reset() {
	*x = CheckIsLikedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIsLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsLikedResponse) ProtoMessage() {}

func (x *CheckIsLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsLikedResponse.ProtoReflect.Descriptor instead.
func (*CheckIsLikedResponse) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{6}
}

func (x *CheckIsLikedResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *CheckIsLikedResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CheckIsLikedResponse) GetLocalError() int64 {
	if x != nil {
		return x.LocalError
	}
	return 0
}

type GetFavoritesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetFavoritesRequest) Reset() {
	*x = GetFavoritesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesRequest) ProtoMessage() {}

func (x *GetFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesRequest.ProtoReflect.Descriptor instead.
func (*GetFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{7}
}

func (x *GetFavoritesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFavoritesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFavoritesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PinAuthor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname  string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl string `protobuf:"bytes,3,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
}

func (x *PinAuthor) Reset() {
	*x = PinAuthor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinAuthor) ProtoMessage() {}

func (x *PinAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinAuthor.ProtoReflect.Descriptor instead.
func (*PinAuthor) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{8}
}

func (x *PinAuthor) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PinAuthor) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PinAuthor) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type FeedPin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PinId      int64      `protobuf:"varint,1,opt,name=pinId,proto3" json:"pinId,omitempty"`
	ContentUrl string     `protobuf:"bytes,2,opt,name=contentUrl,proto3" json:"contentUrl,omitempty"`
	ContentDX  int64      `protobuf:"varint,3,opt,name=contentDX,proto3" json:"contentDX,omitempty"`
	ContentDY  int64      `protobuf:"varint,4,opt,name=contentDY,proto3" json:"contentDY,omitempty"`
	Author     *PinAuthor `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *FeedPin) Reset() {
	*x = FeedPin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedPin) ProtoMessage() {}

func (x *FeedPin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedPin.ProtoReflect.Descriptor instead.
func (*FeedPin) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{9}
}

func (x *FeedPin) GetPinId() int64 {
	if x != nil {
		return x.PinId
	}
	return 0
}

func (x *FeedPin) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *FeedPin) GetContentDX() int64 {
	if x != nil {
		return x.ContentDX
	}
	return 0
}

func (x *FeedPin) GetContentDY() int64 {
	if x != nil {
		return x.ContentDY
	}
	return 0
}

func (x *FeedPin) GetAuthor() *PinAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetFavoritesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pins       []*FeedPin `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
	Valid      bool       `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	LocalError int64      `protobuf:"varint,3,opt,name=localError,proto3" json:"localError,omitempty"`
}

func (x *GetFavoritesResponse) Reset() {
	*x = GetFavoritesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_microservices_like_proto_like_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesResponse) ProtoMessage() {}

func (x *GetFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_microservices_like_proto_like_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesResponse.ProtoReflect.Descriptor instead.
func (*GetFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_internal_microservices_like_proto_like_proto_rawDescGZIP(), []int{10}
}

func (x *GetFavoritesResponse) GetPins() []*FeedPin {
	if x != nil {
		return x.Pins
	}
	return nil
}

func (x *GetFavoritesResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GetFavoritesResponse) GetLocalError() int64 {
	if x != nil {
		return x.LocalError
	}
	return 0
}

var File_internal_microservices_like_proto_like_proto protoreflect.FileDescriptor

var file_internal_microservices_like_proto_like_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6c, 0x69, 0x6b, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x65, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x10, 0x4d, 0x61, 0x6b, 0x65, 0x4c, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x42, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x76, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x77, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x4c,
	0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x14, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5b, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x5d, 0x0a, 0x09, 0x50, 0x69,
	0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x22, 0xa4, 0x01, 0x0a, 0x07, 0x46, 0x65,
	0x65, 0x64, 0x50, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x58, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x44, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x59, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x50,
	0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x22, 0x6f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x50, 0x69, 0x6e, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0xde, 0x02, 0x0a, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x53, 0x65,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x4d, 0x61, 0x6b,
	0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6c,
	0x69, 0x6b, 0x65, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c,
	0x69, 0x6b, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4c,
	0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6c, 0x69, 0x6b,
	0x65, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x4c, 0x69, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64,
	0x12, 0x19, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x4c,
	0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x69,
	0x6b, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x6c, 0x69, 0x6b, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_microservices_like_proto_like_proto_rawDescOnce sync.Once
	file_internal_microservices_like_proto_like_proto_rawDescData = file_internal_microservices_like_proto_like_proto_rawDesc
)

func file_internal_microservices_like_proto_like_proto_rawDescGZIP() []byte {
	file_internal_microservices_like_proto_like_proto_rawDescOnce.Do(func() {
		file_internal_microservices_like_proto_like_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_microservices_like_proto_like_proto_rawDescData)
	})
	return file_internal_microservices_like_proto_like_proto_rawDescData
}

var file_internal_microservices_like_proto_like_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_microservices_like_proto_like_proto_goTypes = []interface{}{
	(*MakeLikeRequest)(nil),       // 0: like.MakeLikeRequest
	(*MakeLikeResponse)(nil),      // 1: like.MakeLikeResponse
	(*GetUsersLikedRequest)(nil),  // 2: like.GetUsersLikedRequest
	(*UserResponse)(nil),          // 3: like.UserResponse
	(*GetUsersLikedResponse)(nil), // 4: like.GetUsersLikedResponse
	(*CheckIsLikedRequest)(nil),   // 5: like.CheckIsLikedRequest
	(*CheckIsLikedResponse)(nil),  // 6: like.CheckIsLikedResponse
	(*GetFavoritesRequest)(nil),   // 7: like.GetFavoritesRequest
	(*PinAuthor)(nil),             // 8: like.PinAuthor
	(*FeedPin)(nil),               // 9: like.FeedPin
	(*GetFavoritesResponse)(nil),  // 10: like.GetFavoritesResponse
}
var file_internal_microservices_like_proto_like_proto_depIdxs = []int32{
	3,  // 0: like.GetUsersLikedResponse.users:type_name -> like.UserResponse
	8,  // 1: like.FeedPin.author:type_name -> like.PinAuthor
	9,  // 2: like.GetFavoritesResponse.pins:type_name -> like.FeedPin
	0,  // 3: like.Like.SetLike:input_type -> like.MakeLikeRequest
	0,  // 4: like.Like.ClearLike:input_type -> like.MakeLikeRequest
	2,  // 5: like.Like.GetUsersLiked:input_type -> like.GetUsersLikedRequest
	5,  // 6: like.Like.CheckIsLiked:input_type -> like.CheckIsLikedRequest
	7,  // 7: like.Like.GetFavorites:input_type -> like.GetFavoritesRequest
	1,  // 8: like.Like.SetLike:output_type -> like.MakeLikeResponse
	1,  // 9: like.Like.ClearLike:output_type -> like.MakeLikeResponse
	4,  // 10: like.Like.GetUsersLiked:output_type -> like.GetUsersLikedResponse
	6,  // 11: like.Like.CheckIsLiked:output_type -> like.CheckIsLikedResponse
	10, // 12: like.Like.GetFavorites:output_type -> like.GetFavoritesResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_microservices_like_proto_like_proto_init() }
func file_internal_microservices_like_proto_like_proto_init() {
	if File_internal_microservices_like_proto_like_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_microservices_like_proto_like_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersLikedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersLikedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIsLikedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIsLikedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFavoritesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinAuthor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedPin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_microservices_like_proto_like_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFavoritesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_microservices_like_proto_like_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_microservices_like_proto_like_proto_goTypes,
		DependencyIndexes: file_internal_microservices_like_proto_like_proto_depIdxs,
		MessageInfos:      file_internal_microservices_like_proto_like_proto_msgTypes,
	}.Build()
	File_internal_microservices_like_proto_like_proto = out.File
	file_internal_microservices_like_proto_like_proto_rawDesc = nil
	file_internal_microservices_like_proto_like_proto_goTypes = nil
	file_internal_microservices_like_proto_like_proto_depIdxs = nil
}
