basePath: api/v1
definitions:
  entity.FeedPinResponse:
    description: PinResponse information with author, pin id and content URL.
    properties:
      author:
        $ref: '#/definitions/entity.PinAuthor'
      content_url:
        type: string
      pin_id:
        type: integer
    type: object
  entity.FeedPins:
    description: Pins array of FeedPinResponse
    properties:
      pins:
        items:
          $ref: '#/definitions/entity.FeedPinResponse'
        type: array
    type: object
  entity.Pin:
    description: Full pin information
    properties:
      allow_comments:
        type: boolean
      click_url:
        type: string
      content_url:
        description: Сделать required для свагера
        type: string
      description:
        type: string
      title:
        type: string
    type: object
  entity.PinAuthor:
    description: User-author information with user id, nickname and avatar
    properties:
      avatar_url:
        type: string
      nickname:
        type: string
      user_id:
        type: integer
    type: object
  entity.PinPageResponse:
    description: Full pin information
    properties:
      allow_comments:
        type: boolean
      author:
        $ref: '#/definitions/entity.PinAuthor'
      click_url:
        type: string
      content_url:
        type: string
      created_at:
        type: string
      description:
        type: string
      likes_count:
        type: integer
      pin_id:
        type: integer
      title:
        type: string
    type: object
  entity.User:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
  entity.UserList:
    description: User information with user id, email, nickname and avatar_url
    properties:
      users:
        items:
          $ref: '#/definitions/entity.UserResponse'
        type: array
    type: object
  entity.UserResponse:
    description: User information with user id, email, nickname and avatar_url
    properties:
      avatar_url:
        type: string
      email:
        type: string
      nickname:
        type: string
      user_id:
        type: integer
    type: object
  errs.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: https://harmoniums.ru
info:
  contact: {}
  description: This is API-docs of backend server of Harmonica team.
  title: Harmonium backend API
  version: "1.0"
paths:
  /is_auth:
    get:
      description: Get user by request cookie
      parameters:
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserResponse'
        "400":
          description: 'Possible code responses: 3.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 2.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Get auth status
      tags:
      - Authorization
  /likes/{pin_id}/users:
    get:
      description: Get users that liked pin by pin ID
      parameters:
      - description: Pin ID
        in: path
        name: pin_id
        required: true
        type: integer
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserList'
        "400":
          description: 'Possible code responses: 12.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Get last 20 users that liked pin
      tags:
      - Likes
  /login:
    post:
      consumes:
      - application/json
      description: Login user by request.body json
      parameters:
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: 'Possible code responses: 3, 4, 5.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 7, 8.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "403":
          description: 'Possible code responses: 1.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Login user
      tags:
      - Authorization
  /logout:
    get:
      description: Logout user by their session cookie
      parameters:
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible code responses: 3.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Logout user
      tags:
      - Authorization
  /pins:
    get:
      description: Get pins by page
      parameters:
      - description: Page num from 0
        in: query
        name: page
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.FeedPins'
        "400":
          description: 'Possible code responses: 4.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Pins list
      tags:
      - Pins
  /pins/{pin_id}:
    delete:
      description: Delete pin by id (allowed only for pin's author)
      parameters:
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        required: true
        type: string
      - description: Pin ID
        in: path
        name: pin_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PinPageResponse'
        "400":
          description: 'Possible code responses: 3, 4 12'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 2.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "403":
          description: 'Possible code responses: 14.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Delete pin
      tags:
      - Pins
    get:
      description: Get pin by id in the slug
      parameters:
      - description: Pin ID
        in: path
        name: pin_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PinPageResponse'
        "400":
          description: 'Possible code responses: 4, 12.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Get pin by id
      tags:
      - Pins
    post:
      consumes:
      - application/json
      description: Update pin by description
      parameters:
      - description: Pin information
        in: body
        name: pin
        required: true
        schema:
          $ref: '#/definitions/entity.Pin'
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PinPageResponse'
        "400":
          description: 'Possible code responses: 3, 4, 12'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 2.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "403":
          description: 'Possible code responses: 14.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Update pin
      tags:
      - Pins
  /pins/{pin_id}/like:
    delete:
      description: Delete like by pin id and auth token
      parameters:
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        required: true
        type: string
      - description: Pin ID
        in: path
        name: pin_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible code responses: 3, 12.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 2.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Delete like on the pin
      tags:
      - Likes
    post:
      description: Sets like by pin id and auth token
      parameters:
      - default: session-token=
        description: session-token
        in: header
        name: Cookie
        required: true
        type: string
      - description: Pin ID
        in: path
        name: pin_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: 'Possible code responses: 3, 12.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 2.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Set like on the pin
      tags:
      - Likes
  /pins/created/{nickname}:
    get:
      description: Get pins of user by page
      parameters:
      - description: Page num from 0
        in: query
        name: page
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.FeedPins'
        "400":
          description: 'Possible code responses: 4, 12.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Get pins that created by user id
      tags:
      - Pins
  /users:
    post:
      consumes:
      - application/json
      description: Register user by POST request and add them to DB
      parameters:
      - description: json
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserResponse'
        "400":
          description: 'Possible code responses: 3, 4, 5.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 7, 8.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "403":
          description: 'Possible code responses: 1.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Register user
      tags:
      - Authorization
  /users/{user_id}:
    post:
      consumes:
      - application/json
      description: Update user by description and user id.
      parameters:
      - description: User information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PinPageResponse'
        "400":
          description: 'Possible code responses: 3, 4, 5, 12, 13'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "401":
          description: 'Possible code responses: 2.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "403":
          description: 'Possible code responses: 14.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
        "500":
          description: 'Possible code responses: 6, 11.'
          schema:
            $ref: '#/definitions/errs.ErrorResponse'
      summary: Update user
      tags:
      - Users
swagger: "2.0"
