name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_CERT }}
          SSH_CMD_ARGS: "-o StrictHostKeyChecking=no -o ConnectTimeout=30"
          ARGS: "-v -i"
          REMOTE_HOST: 85.192.35.36
          REMOTE_USER: ubuntu
          SCRIPT_BEFORE: cd /home/ubuntu/project/2024_1_Harmonica_BACK ; sudo nohup make deploy 
          SCRIPT_AFTER: echo "Deployed successfully."
      