name: Deploy apple
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 85.192.35.36
          username: ubuntu
          key: ${{ secrets.DEPLOY_CERT }}
          script: cd /home/ubuntu/project/2024_1_Harmonica_BACK ; sudo nohup make deploy < /dev/null > /tmp/deploy.log 2>&1 &