name: Run linters
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: --config=linter/.golangci.toml --timeout=30m
          only-new-issues: true
