name: Run linters and tests
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: ["*"]
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: --config=linter/.golangci.toml --timeout=30m --skip-dirs='(tests)'
#  tests:
#      runs-on: ubuntu-latest
#      steps:
#      - uses: actions/checkout@v4
#  
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: '1.22'
#  
#      - name: Build
#        run: go build -v ./...
#  
#      - name: Test
#        run: make test
